[versions]

ktor = "2.1.0"

fabric-loader = "0.17.3"
fabric-kotlin = "1.13.0+kotlin.2.1.0"

universalcraft = "436"
elementa = "local-SNAPSHOT"
vigilance = "312"

[libraries]

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version = "1.2.1" }

elementa = { module = "gg.essential:elementa", version.ref = "elementa" }
vigilance = { module = "gg.essential:vigilance", version.ref = "vigilance" }
jukebox = { module = "tech.thatgravyboat:jukebox-jvm", version = "1.0.2" }
ktor-cio = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktor" }
ktor-events = { module = "io.ktor:ktor-events-jvm", version.ref = "ktor" }
ktor-http-cio = { module = "io.ktor:ktor-http-cio-jvm", version.ref = "ktor" }
ktor-http = { module = "io.ktor:ktor-http-jvm", version.ref = "ktor" }
ktor-io = { module = "io.ktor:ktor-io-jvm", version.ref = "ktor" }
ktor-network = { module = "io.ktor:ktor-network-jvm", version.ref = "ktor" }
ktor-network-tls = { module = "io.ktor:ktor-network-tls-jvm", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-jvm", version.ref = "ktor" }
ktor-utils = { module = "io.ktor:ktor-utils-jvm", version.ref = "ktor" }
ktor-websocket-serialization = { module = "io.ktor:ktor-websocket-serialization-jvm", version.ref = "ktor" }
ktor-websockets = { module = "io.ktor:ktor-websockets-jvm", version.ref = "ktor" }

olympus-lib1215 = { module = "earth.terrarium.olympus:olympus-fabric-1.21.5", version = "1.3.6" }
olympus-lib1219 = { module = "earth.terrarium.olympus:olympus-fabric-1.21.9", version = "1.6.2" }

resourceful-lib1215 = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21.5", version = "3.5.0" }
resourceful-lib1219 = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21.9", version = "3.9.1" }

[plugins]

terrarium-cloche = { id = "earth.terrarium.cloche", version = "0.16.11" }
classextensions = { id = "net.msrandom.classextensions", version = "1.0.11" }

[bundles]

ktor = [
    "ktor-cio",
    "ktor-core",
    "ktor-events",
    "ktor-http-cio",
    "ktor-http",
    "ktor-io",
    "ktor-network",
    "ktor-network-tls",
    "ktor-serialization",
    "ktor-utils",
    "ktor-websocket-serialization",
    "ktor-websockets"
]