[versions]

ktor = "2.1.0"

fabric-loader = "0.17.3"
fabric-api = "0.154.2+26.2"
fabric-kotlin = "1.13.0+kotlin.2.1.0"

minecraft = "26.2"

universalcraft = "505"
elementa = "745"
vigilance = "314"

[libraries]

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version = "1.2.2" }

ktor-cio = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktor" }
ktor-events = { module = "io.ktor:ktor-events-jvm", version.ref = "ktor" }
ktor-http-cio = { module = "io.ktor:ktor-http-cio-jvm", version.ref = "ktor" }
ktor-http = { module = "io.ktor:ktor-http-jvm", version.ref = "ktor" }
ktor-io = { module = "io.ktor:ktor-io-jvm", version.ref = "ktor" }
ktor-network = { module = "io.ktor:ktor-network-jvm", version.ref = "ktor" }
ktor-network-tls = { module = "io.ktor:ktor-network-tls-jvm", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-jvm", version.ref = "ktor" }
ktor-utils = { module = "io.ktor:ktor-utils-jvm", version.ref = "ktor" }
ktor-websocket-serialization = { module = "io.ktor:ktor-websocket-serialization-jvm", version.ref = "ktor" }
ktor-websockets = { module = "io.ktor:ktor-websockets-jvm", version.ref = "ktor" }

jukebox = { module = "tech.thatgravyboat:jukebox-jvm", version = "1.0.2" }

universalcraft = { module = "gg.essential:universalcraft-26.2-fabric", version.ref = "universalcraft" }
elementa = { module = "gg.essential:elementa", version.ref = "elementa" }
vigilance = { module = "gg.essential:vigilance", version.ref = "vigilance" }

olympus = { module = "earth.terrarium.olympus:olympus-fabric-26.2", version = "1.9.0" }
resourceful-lib = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-26.2", version = "5.0.1" }

[plugins]

loom = { id = "net.fabricmc.fabric-loom", version = "1.15-SNAPSHOT" }
shadow = { id = "com.gradleup.shadow", version = "9.3.0" }

[bundles]

ktor = [
    "ktor-cio",
    "ktor-core",
    "ktor-events",
    "ktor-http-cio",
    "ktor-http",
    "ktor-io",
    "ktor-network",
    "ktor-network-tls",
    "ktor-serialization",
    "ktor-utils",
    "ktor-websocket-serialization",
    "ktor-websockets"
]